### ISSUE TITLE
Patched mapnik still necessary? Missing xml files in templates/ 

### ISSUE THREAD

**Issue by bnordgren** [Ahlzen/TopOSM#7]
Thanks for all your hard work! I'm having some luck getting this to run on the regular packages associated with Ubuntu 16.04. I intend to make a docker image out of this when I get done. One question, though: is it still necessary to build a patched version of mapnik, or did the patch find its way into Mapnik 3? 

Now to the "bug": First, I'm using the fork by @asciiphil because it seems to have seen more recent activity than this repo; but there seems to be no "issues" tab in that repository. When I run `./toposm.py png <Area> <file> <x> <y>` at the end of the process, quite a lot of the layers are missing xml files. Would it be possible to get templates for these committed to the @asciiphil repo? 

```
root@55a88d6c6941:/home/bryce/TopOSM# ./toposm.py png Mineral test.png 5000 5000
 Rendering layers
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "./toposm.py", line 390, in run
    mapnik.load_map(map, self.mapname + ".xml")
RuntimeError: Could not load map file: File does not exist of 'features_top.xml'
```

This repeats for all of: 

```
RuntimeError: Could not load map file: File does not exist of 'features_top.xml'
RuntimeError: Could not load map file: File does not exist of 'features_labels.xml'
RuntimeError: Could not load map file: File does not exist of 'contour-labels.xml'
RuntimeError: Could not load map file: File does not exist of 'features_mask.xml'
RuntimeError: Could not load map file: File does not exist of 'features_fills.xml'
RuntimeError: Could not load map file: File does not exist of 'contour-mask.xml'
RuntimeError: Could not load map file: File does not exist of 'features_outlines.xml'
```

I can remove these layers from `MAPNIK_LAYERS` for now, but at least one (contour-mask) is hardcoded somewhere else. Besides, it'd be nice to see what kind of map these missing files produce. :) 

Thanks again!

**Comment by Ahlzen** [comment]
Hi,

Sorry about the really late reply. This has been a bit of a busy week for
me.

Were you able to make it work with Phil's branch? It's been a while since I
worked on that project, but after running the script that generates the xml
files, they should be there iirc.

- Lars

On Dec 10, 2016 07:05, "bnordgren" <notifications@github.com> wrote:

Thanks for all your hard work! I'm having some luck getting this to run on
the regular packages associated with Ubuntu 16.04. I intend to make a
docker image out of this when I get done. One question, though: is it still
necessary to build a patched version of mapnik, or did the patch find its
way into Mapnik 3?

Now to the "bug": First, I'm using the fork by @asciiphil
<https://github.com/asciiphil> because it seems to have seen more recent
activity than this repo; but there seems to be no "issues" tab in that
repository. When I run ./toposm.py png <Area> <file> <x> <y> at the end of
the process, quite a lot of the layers are missing xml files. Would it be
possible to get templates for these committed to the @asciiphil
<https://github.com/asciiphil> repo?

root@55a88d6c6941:/home/bryce/TopOSM# ./toposm.py png Mineral test.png 5000 5000
 Rendering layers
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "./toposm.py", line 390, in run
    mapnik.load_map(map, self.mapname + ".xml")
RuntimeError: Could not load map file: File does not exist of 'features_top.xml'

This repeats for all of:

RuntimeError: Could not load map file: File does not exist of 'features_top.xml'
RuntimeError: Could not load map file: File does not exist of
'features_labels.xml'
RuntimeError: Could not load map file: File does not exist of
'contour-labels.xml'
RuntimeError: Could not load map file: File does not exist of
'features_mask.xml'
RuntimeError: Could not load map file: File does not exist of
'features_fills.xml'
RuntimeError: Could not load map file: File does not exist of 'contour-mask.xml'
RuntimeError: Could not load map file: File does not exist of
'features_outlines.xml'

I can remove these layers from MAPNIK_LAYERS for now, but at least one
(contour-mask) is hardcoded somewhere else. Besides, it'd be nice to see
what kind of map these missing files produce. :)

Thanks again!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Ahlzen/TopOSM/issues/7>, or mute the thread

**Comment by bnordgren** [comment]
Well I got it to work by omitting the missing templates. The XML generating script pretty much just takes templates in the `include` and `templates` directories and makes new files of the same base name (minus the *.templ extension). The XML files listed above have no corresponding *.templ file. I guess they never got checked in.

I started with Phil's branch mostly because it looked like it had significant work after this repository ended. Unfortunately, I rolled back a fair amount of that because it looked to me like he pre-rendered some highway signs and included the filename to the result in the PostGIS database.

To answer my other question, Mapnik 3 seems to make maps without the patch. :) Purty maps. Will close this issue due to the presence of workarounds.
